# -*- coding: utf-8 -*-
"""Proyecto_Farma.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vwe3nt_KensdYpGBIh44oGgI23CVZk58
"""

# Conecta con el drive cuando la funcion manual da problemas

from google.colab import drive
drive.mount('/content/drive')

# Importar librerias y data sets ubicados en el drive

import pandas as pd

df1 = pd.read_csv("/content/drive/MyDrive/Proyecto Farmaceutico/CÓDIGO_ÚNICO_DE_MEDICAMENTOS_VIGENTES_20251116.csv")

df2 =pd.read_csv("/content/drive/MyDrive/Proyecto Farmaceutico/medicamentos_20251116.csv")

df3 = pd.read_csv("/content/drive/MyDrive/Proyecto Farmaceutico/df3_SinModificar.csv")

# Verifica los tipos de datos, verificacion de informacion
df1.info()
df2.info()
df3.info()

# Verificar Valores Nulos en los 3 data sets usados

ver_nulos_df1 = df1.isnull().sum()
display(ver_nulos_df1)
ver_nulos_df2 = df2.isnull().sum()
display(ver_nulos_df2)
ver_nulos_df3 = df3.isnull().sum()
display(ver_nulos_df3)

## Creacion de una nueva columna con el codigo CUM completo del df1 (expedientecum-consecutivo), para poder luego correlacionar los df1

df1["expediente_consecutivo"] = df1["expedientecum"].astype(str) + "-" + df1["consecutivocum"].astype(str)
df1 = df1.rename(columns={"expediente_consecutivo": "CUM"})

# Unir df1 con df3 usando el CUM como valor de correlacion y eliminando el merge_flag que deja automaticamente la migracion

df1 = df1.merge(
    df3,
    on="CUM",
    how="left",           # conserva todos los registros de df
    suffixes=("", "_df3"),# por si hay nombres de columnas repetidos
    indicator="merge_flag"
)

# Contar cuántos CUM coincidieron y cuántos no
coinciden = (df1["merge_flag"] == "both").sum()
no_coinciden = (df1["merge_flag"] == "left_only").sum()

print("Registros con CUM coincidente:", coinciden)
print("Registros sin coincidencia:", no_coinciden)

df1 = df1.drop(columns=["merge_flag"])

# Traer los datos del df2 al df1, mediante la coincidencia del principio activo

# Crear una versión normalizada (simple) del principio activo en ambos df
df1["principio_norm"] = df1["principioactivo"].str.strip().str.lower()
df2["principio_norm"] = df2["principio_activo"].str.strip().str.lower()

# Hacer el merge: traer TODAS las columnas de df2 a df1
df_unido = df1.merge(
    df2,
    on="principio_norm",
    how="left",
    suffixes=("", "_df2"),
    indicator="merge_flag"
)

# Contar cuántos registros de df1 encontraron match en df2
coinciden2 = (df_unido["merge_flag"] == "both").sum()
print("Registros Coincidentes", coinciden2)

# Borrar Columnas que no seran utiles para el analisis del nuevo data set (df_unido)
columns_to_drop = ['expediente','registrosanitario','fechaactivo','fechavencimiento', 'estadoregistro','expedientecum', 'consecutivocum',
                    'cantidadcum','estadocum','atc', 'modalidad', 'IUM','No', 'ID MR','Mercado Relevante','Circular CNPMDM',
                   'fechainactivo', 'muestramedica','Fecha de inicio vigencia precio máximo de venta', 'merge_flag','principio_norm','factoresprecio','numerofactor']

df_unido.drop(columns=columns_to_drop, inplace=True)

# Verificar las columnas y sus nombres con las cuales ha quedado el df_unido finalmente
df_unido.columns

# Identificar los valores CUM unicos y repetidos y luego borra los repetidos del df_unido

# Ver Valores CUM Unicos
num_cum_unicos = df_unido["CUM"].nunique()
print("Medicamentos con CUM unico",num_cum_unicos)

# Ver Valores CUM Repetidos
num_cum_duplicados = df_unido["CUM"].duplicated(keep=False).sum()
print("Medicamentos con CUM duplicado", num_cum_duplicados)

# Borrar registros repedidos
df_unido = df_unido.drop_duplicates(subset=["CUM"], keep="first")

# Hacer una verificacion visual rapida de como quedo el df_unido filanmente despues de las modificaciones realizadas, asi como una verificacion del tamanio final el df

display(df_unido.shape)
display(df_unido.head(5))

ver_nulos_df = df_unido.isnull().sum()
display(ver_nulos_df)
df_unido.shape

# Exportar la nueva data set unida  df_unida a la carpeta drive.

output_path = '/content/drive/MyDrive/Proyecto Farmaceutico/df_unido.csv'
df_unido.to_csv(output_path, index=False)